name: HelseID Registrering
description: Registrer en applikasjon i HelseId for produksjon
title: "[AppNavn]:"
labels: ["Fullt navn på applikasjonen", "2"]
projects: ["Whatever"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Endelig tid for å sette galskapen i produksjon!  Fyll ut dette, så blir dokumentasjonen din generert, og levert til HelseId.
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Hva slags type applikasjon skal du registrere?
      options:
        - WebKlient (Default)
        - MaskinKlient
        - Api
      default: 0
    validations:
      required: true
  - type: dropdown
    id: api
    attributes:
      label: Mitt Api kaller andre Api'er.
      description: Dersom du valgte Api ovenfor, skal ditt Api kalle andre Api'er? 
      options:
        - Ja
        - Nei
      default: 1
  - type: dropdown
    id: webklient
    attributes:
      label: Min WebKlient Backend kaller andre Api'er.
      description: Dersom du valgte WebKlient ovenfor, skal din WebKlient kalle andre Api'er? 
      options:
        - Ja
        - Nei
      default: 1
  - type: dropdown
    id: dpop
    attributes:
      label: Bruk av DPop
      description: Krever Api'ene du skal kalle DPop?
      options:
        - Ja
        - Nei
      default: 1
  - type: dropdown
    id: brukeritoken
    attributes:
      label: Accesstoken inneholder innlogget bruker
      description: Krever API informasjon om innlogget bruker i token?
      options:
        - Ja
        - Nei
      default: 1
  - type: dropdown
    id: drift
    attributes:
      label: Driftsmiljo
      description: Hvor skal applikasjonen driftes?
      options:
        - NDL
        - NDL v2 (privat sky)
        - Etatsplattformen yellow (Ordinær sone)
        - Etatsplattformen dmz 
        - Etatsplattformen purple 
        - Etatsplattformen red (Sikker sone)
        - TSD UiO
        - EduCloud UiO
        - Hunt NTNU
        - Azure med Helsenett 
        - Azure uten Helsenett
      default: 0    
  - type: input
    id: sourcecode
    attributes:
      label: Link til source code 
      description: Oppgi repository eller folder dersom flere apper i samme repo. 
      placeholder: https://dev.azure.com/fhi/Fhi.Felles/Whatever
    validations:
      required: true
  - type: dropdown
    id: nda
    attributes:
      label: Krever FHI NDA
      description: Om kildekode ligger hos Fhi og ikke er open source kreves NDA, som Nhn må levere inn av de som eventuelt skal granske koden
      options:
        - Ja
        - Nei
      default: 0
  - type: input
    id: modell
    attributes:
      label: Link til modell tegning 
      description: Eventuelt. Oppgi link til wiki eller bilde. Kan også legges inn i repo her. Om ikke skriv kommentar under.
      placeholder: https://dev.azure.com/fhi/Fhi.Felles/_wiki/wikis/Fhi.Felles.wiki/4507/Neseblod
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Kommentarer
      description: Er det noen ekstra informasjon som du vil ha med?
    validations:
      required: false



